In [1]:
import numpy as np

In [2]:
ar = np.array([1,2,3,4])
print(ar)
print(type(ar), ar.dtype,sep=" : ")
ar = np.array([[1,'2','3'],[4,5,6],[7,8,9]])
print(ar)
print(type(ar), ar.dtype,sep=" : ")

ar = np.array([[1,'2','3'],[4,5,6],[7,8,9]],dtype=int)
print(ar)
print(type(ar), ar.dtype,sep=" : ")

[1 2 3 4]
<class 'numpy.ndarray'> : int64
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
<class 'numpy.ndarray'> : <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'> : int64


In [3]:
ar = np.array([[1,'2','3'],[4,5,6],[7,8,9]],dtype=int)
print(ar.ndim)
print(ar.shape)
print(ar.size)

2
(3, 3)
9


In [4]:
print("___ All Zeroes ___ 2X3",np.zeros((2,3)),"___ All Zeroes ___ 3X3",np.zeros((3,3)),sep="\n")
print("___ All Ones ___ 3X4",np.ones((3,4)),sep="\n")
print("___ Identity Matrix ___ 2X2",np.eye(2),sep="\n")
print(f"Range : {np.arange(-3,7)}")
print("Line Space : ",np.linspace(0,10,6,endpoint=True))

___ All Zeroes ___ 2X3
[[0. 0. 0.]
 [0. 0. 0.]]
___ All Zeroes ___ 3X3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
___ All Ones ___ 3X4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
___ Identity Matrix ___ 2X2
[[1. 0.]
 [0. 1.]]
Range : [-3 -2 -1  0  1  2  3  4  5  6]
Line Space :  [ 0.  2.  4.  6.  8. 10.]


In [5]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Array Slicing
# print(ar[0])
# print(ar[0:2]);print(ar[0][1:2])

# Column
print(ar[0,1])
print(ar[:,0])

# Vectorizing
print(ar+10)
print(ar*2)

2
[1 4 7]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [45]:
# Basic Math Functions
print(f"Sum of the array : {np.sum(ar)}")
print(f"Mean of the array : {np.mean(ar)}")
print(f"Standard Difference of the array : {np.std(ar)}")
print(f"Max Number of the array : {np.max(ar)}")
print(f"Minimum Number of the array : {np.min(ar)}")
print(f"Median of the array : {np.median(ar)}")
print(f"Index of maximum value : {np.argmax(ar)}")
print(f"Index of minimum value : {np.argmin(ar)}")

Sum of the array : 45
Mean of the array : 5.0
Standard Difference of the array : 2.581988897471611
Max Number of the array : 9
Minimum Number of the array : 1
Median of the array : 5.0
Index of maximum value : 8
Index of minimum value : 0


In [7]:
# Reshaping
arr = np.arange(6)
print(arr)
print(arr.reshape(2,3))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [8]:
arr = np.arange(1,21)
print(arr)
arr = arr.reshape(4,5)
print(arr)
print(arr.shape)
print(arr[0])
print(arr[:,0])
print(arr+100)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)
[1 2 3 4 5]
[ 1  6 11 16]
[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]]


In [9]:
ar2 = np.arange(10,50,5)
print(ar2)
print(ar2[3:5])
print(ar2*3)
print(ar2.reshape(2,-1)) # let numpy decide
ar2 = ar2.reshape(2,4)
print(ar2)


[10 15 20 25 30 35 40 45]
[25 30]
[ 30  45  60  75  90 105 120 135]
[[10 15 20 25]
 [30 35 40 45]]
[[10 15 20 25]
 [30 35 40 45]]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(np.vstack([a,b]))
print(np.hstack([a,b]))
print(np.split(a,1))
print(np.split(a,2))
print(np.split(a,4))

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]
[array([1, 2, 3, 4])]
[array([1, 2]), array([3, 4])]
[array([1]), array([2]), array([3]), array([4])]


| Function      | What it does                        |
| ------------- | ----------------------------------- |
| `np.dot(a,b)` | Vector dot OR matrix multiplication |
| `np.sqrt(a)`  | Square root (element-wise)          |
| `np.exp(a)`   | e^x (element-wise)                  |
| `np.log(a)`   | Natural log (element-wise)          |


In [43]:
print(np.dot(a,b))
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(np.dot(a,b))

60
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[[19 22]
 [43 50]]


In [ ]:
mat = np.array([[1,2,3],[4,5,6],[7,8,10]])
print(np.linalg.inv(mat)) # inverse of a matrix 
print(np.linalg.det(mat)) # Determinant of a matrix
print(np.linalg.eig(mat)) # Eigenvalues & Eigenvectors
print(np.linalg.eigh([[1,2],[2,1]])) # Only for symentric or Hermitian Matrices

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
-2.9999999999999996
EigResult(eigenvalues=array([16.70749332, -0.90574018,  0.19824686]), eigenvectors=array([[-0.22351336, -0.86584578,  0.27829649],
       [-0.50394563,  0.0856512 , -0.8318468 ],
       [-0.83431444,  0.4929249 ,  0.48018951]]))
EighResult(eigenvalues=array([-1.,  3.]), eigenvectors=array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]]))
