In [1]:
import numpy as np
import pandas as pd

In [25]:
image = np.array([[100, 150], [200, 230]])
image2 = np.clip(image + 50, 0, 255)
print(image2)

[[150 200]
 [250 255]]


In [26]:
s = np.array([10, 20, -15, 55, 30, 45])
s2 = s[(s >= -10) & (s <= 50)]
print(s2)

[10 20 30 45]


In [27]:
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / \
             (np.max(data) - np.min(data))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [29]:
sales = np.array([
    [100, 200, 150, 300, 250, 400, 350],
    [80, 120, 160, 200, 220, 260, 300],
    [50, 70, 90, 110, 130, 150, 170]
])

total_per_store = np.sum(sales, axis=1)
avg_per_day = np.mean(sales, axis=0)
print(sales)
print(total_per_store)
print(avg_per_day)

[[100 200 150 300 250 400 350]
 [ 80 120 160 200 220 260 300]
 [ 50  70  90 110 130 150 170]]
[1750 1340  770]
[ 76.66666667 130.         133.33333333 203.33333333 200.
 270.         273.33333333]


In [6]:
user = np.array([[1, 0], [0, 1]])
product= np.array([[5, 10], [2, 3]])

recommendation = np.dot(user, product)

print(recommendation)

[[ 5 10]
 [ 2  3]]


In [31]:
df_orders = pd.DataFrame({
    "order_id": [1,2,3,4],
    "customer": ["A","B","C","D"],
    "amount": [100, 200, 150, 300],
    "status": ["completed", "pending", "completed", "completed"]
})

completed = df_orders[df_orders["status"] == "completed"]

total_revenue = completed["amount"].sum()

top3 = df_orders.sort_values(by="amount", ascending=False).head(5)

print(completed)
print(total_revenue)
print(top3)

   order_id customer  amount     status
0         1        A     100  completed
2         3        C     150  completed
3         4        D     300  completed
550
   order_id customer  amount     status
3         4        D     300  completed
1         2        B     200    pending
2         3        C     150  completed
0         1        A     100  completed


In [32]:
df_emp = pd.DataFrame({
    "employee": ["A","B","C","D"],
    "department": ["HR","IT","HR","IT"],
    "salary": [30000, 50000, 35000, 60000]
})

avg_salary = df_emp.groupby("department")["salary"].mean()

highest_dept = avg_salary.idxmax()
print(df_emp)
print(avg_salary)
print(highest_dept)

  employee department  salary
0        A         HR   30000
1        B         IT   50000
2        C         HR   35000
3        D         IT   60000
department
HR    32500.0
IT    55000.0
Name: salary, dtype: float64
IT


In [33]:
df_missing = pd.DataFrame({
    "A": [1, None, 3],
    "B": [4, 5, None]
})

missing = df_missing.isnull()

filled = df_missing.fillna(df_missing.mean())
print(missing)
print(filled)

       A      B
0  False  False
1   True  False
2  False   True
     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5


In [34]:
df_logs = pd.DataFrame({
    "timestamp": pd.to_datetime(["2023-01-01", "2023-05-01", "2023-08-01", "2024-01-01"],),
    "log_message": ["INFO start", "ERROR failed","ERROR" , "ERROR crash"]
})

df_logs["year"] = df_logs["timestamp"].dt.year

errors = df_logs[df_logs["log_message"].str.contains("ERROR")]

error_count = errors.groupby("year").size()

print(errors)
print(error_count)

   timestamp   log_message  year
1 2023-05-01  ERROR failed  2023
2 2023-08-01         ERROR  2023
3 2024-01-01   ERROR crash  2024
year
2023    2
2024    1
dtype: int64


In [35]:
customers = pd.DataFrame({
    "customer_id": [1,2],
    "name": ["A","B"]
})

orders = pd.DataFrame({
    "customer_id": [1,1,2],
    "amount": [100, 150, 200]
})

merged = pd.merge(customers, orders, on="customer_id")

total_purchase = merged.groupby("customer_id")["amount"].sum()
print(merged)
print(total_purchase)

   customer_id name  amount
0            1    A     100
1            1    A     150
2            2    B     200
customer_id
1    250
2    200
Name: amount, dtype: int64
